### ISSUE TITLE
Annotations TODO

### ISSUE THREAD

**Issue by alessandrodicosola** [alessandrodicosola/NAI#14]
- [x] dicom paz 0.zip
---
- [x] 20210727/1.zip 
---
- [x] 20210903/1.zip replace 1.76.380.18.14.1160727161946.19210903101503808.81
- [x] 20210903/2.zip 🛑
- [x] 20210903/3.zip  LX: missing annotations from 530 - 518 
- [x] 20210903/4.zip 🛑
---
- [x] 20210916/6.zip
---
- [x] 20210918/7.zip
- [x] 20210918/8.zip
---
- [x] 20211013/10.zip
---
- [x] 20211014/11.zip
- [x] 20211014/14.zip
---
- [x] 20211015/15.zip
- [x] 20211015/16.zip
- [x] 20211015/17.zip - 🛑 - ONLY LEFT
- [x] 20211015/18.zip
---
- [x] 20211019/b1.zip - 🛑
- [x] 20211019/b4.zip
---
- [x] 20211027/z1.zip
- [x] 20211027/z2.zip - ONLY LEFT
- [x] 20211027/z3.zip - 1
- [x] 20211027/z3.zip - 2 🛑
- [x] 20211027/z4.zip
- [x] 20211027/z5.zip ✅
- [x] 20211027/z6.zip
---
- [x] 20211108/z8.zip
- [x] 20211108/z9.zip
- [x] 20211108/z10.zip
- [x] 20211108/z11.zip
---
- [x] 20211118/z13.zip - 🛑
- [x] 20211118/z16.zip
- [x] 20211118/z17.zip
---
- [x] 20211129/z18.zip
- [x] 20211129/z19.zip
- [x] 20211129/z21.zip
- [x] 20211129/z22.zip
---
- [x] 20211130/z23.zip ✅
- [x] 20211130/z24.zip
- [x] 20211130/z25.zip
---
- [x] 20211201/z27.zip
- [x] 20211201/z28.zip
- [x] 20211201/z29.zip
- [x] 20211201/z31.zip
- [x] 20211201/z32.zip
- [x] 20211201/z33.zip
---
- [x] 20211217/z28.zip [1180*.4134] - No entrance at right
- [x] 20211217/z29.zip [*.4860] - 🛑
- [x] 20211217/z30.zip [1180*.5058] - 🛑Mostly black 
- [x] 20211217/z31.zip
- [x] 20211217/z32.zip
- [x] 20211217/z33.zip [1180*.5690] - 🛑
- [x] 20211217/z34.zip
- [x] 20211217/z35.zip
- [x] 20211217/z36.zip [1180*.5675] - ✅
- [x] 20211217/z38.zip
- [x] 20211217/z39.zip
- [x] 20211217/z41.zip
- [x] 20211217/z42.zip
- [x] 20211217/z45.zip
- [x] 20211217/z46.zip - No entrance presents
---
- [x] 20211222/z47.zip
- [x] 20211222/z49.zip
- [x] 20211222/z50.zip
- [x] 20211222/z51.zip
- [x] 20211222/z52.zip
- [x] 20211222/z54.zip
- [x] 20211222/z55.zip
- [x] 20211222/z56.zip [1180*.668] - 🛑 Only rx
- [x] 20211222/z57.zip
- [x] 20211222/z59.zip [1180*.1223] - Only lx
- [x] 20211222/z60.zip
- [x] 20211222/z61.zip

* ⚠ = Not sure about annotations
* 🛑 = Not sure about annotations. Probably should not be used for training.
* ✅ = Very good annotations

**Comment by alessandrodicosola** [comment]
**Copy**
- [x] 20211014/12.zip 
- [x] 20211014/13.zip 
- [x] 20211019/b2.zip 
- [x] 20211116/b1.zip
- [x] 20211116/b2.zip
- [x] 20211116/b3.zip
- [x] 20211116/b4.zip
- [x] 20211118/z15.zip 
- [x] 20211129/z20.zip
- [x] 20211217/z43.zip [1180*.2679]
- [x] 20211217/z44.zip [1180*.4678]
- [x] 20211222/z48.zip [1180*.3479]

**Unusable**
- [x] 20211013/9.zip - stretched vertically 
- [x] 20211108/z7.zip - Impossible to detect nerve
- [x] 20211108/z12.zip - Impossible to detect nerve
- [x] 20211116/b5.zip - low brightness; nerve is impossible to see; no entrance
- [x] 20211118/z14.zip - It's impossible to see the canal in the middle
- [x] 20211130/z26.zip
- [x] 20211201/z30.zip
- [x] 20211217/z37.zip - No exit in both lx and rx.
- [x] 20211217/z40.zip - low brightness; nerve is impossible to see; 
- [x] 20211222/z53.zip [1180*.1681] - Low brightness; No entrance
- [x] 20211222/z58.zip [1180*.5004]

**Comment by alessandrodicosola** [comment]
Remove 20211019/b3.zip from **annotations folder**
